### ISSUE TITLE
Add support for FSP_FUSE_CAP_READDIR_PLUS

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/fusepy#1]
Add support for `FSP_FUSE_CAP_READDIR_PLUS` when running on Windows or Cygwin under WinFsp-FUSE.

See:

- billziss-gh/winfsp/issues/22.
- billziss-gh/winfsp/issues/44.

**Comment by billziss-gh** [comment]
Commit d03ca8f59d609f1d68136fd7a18ab055f58b599c fixes this issue. This is currently in the [windows](https://github.com/billziss-gh/fusepy/tree/windows) branch.

@tstordyallison please let me know if this works for you.

**Comment by tstordyallison** [comment]
Thanks - will try to give this a go this weekend!

**Comment by billziss-gh** [comment]
@tstordyallison did you ever have the chance to try this? If it works for you as well, I will probably go ahead and merge the changes into master.

**Comment by tstordyallison** [comment]
Yes - sorry meant to reply here earlier! Works for me.

I had actually got this working with some changes of my own to fusepy, so I just wanted to check these worked in a similar way.

I still get lots of getattr and readdir that are 'cache hits' for a cache I maintain internally, but it's much better than before. 

I'm going to spend some more time profiling fusepy/what I have to see where the majority of the overhead is. I fear ctypes in addition to some of the repeated readdir/getattr may just be too much to do from straight python.

**Comment by billziss-gh** [comment]
Thanks for the feedback.

> I'm going to spend some more time profiling fusepy/what I have to see where the majority of the overhead is. I fear ctypes in addition to some of the repeated readdir/getattr may just be too much to do from straight python.

Please let me know when you have this information as I would love to see it and see how we can further improve fusepy and maybe WinFsp-FUSE.

BTW, WinFsp latest version now has `-oFileInfoTimeout=1000` by default, so that is another reason you should hopefully see less `getattr` calls than before.
