### ISSUE TITLE
can't pass st_file_attributes back

### ISSUE THREAD

**Issue by robert-boulanger** [billziss-gh/fusepy#11]
As seen in https://github.com/billziss-gh/winfsp/issues/114 it seems support for windows file attributes should be present.
The question is how to implement them in a proper way in fuse.py,or what changes are needed to make there.
Unfortunatly setting st_mode to S_IFREG | 0o555 for example is not enough. This would cause the file is readonly but lot of software seems to rely on the windows attributes to work proper.
Any hint how to modify fuse.py would be great.

**Comment by billziss-gh** [comment]
@robert-boulanger I have not thought this through, but it is likely that you can get it done by modifying [`c_stat`](https://github.com/billziss-gh/fusepy/blob/master/fuse.py#L295) to add `st_flags` and passing the `FSP_FUSE_CAP_STAT_EX` (`1 << 23`) in [`self.conn_want`](https://github.com/billziss-gh/fusepy/blob/master/fuse.py#L525).

If you make this work please consider sharing.

**Comment by robert-boulanger** [comment]
@billziss-gh That worked fine, so changing [self.conn_want](https://github.com/billziss-gh/fusepy/blob/master/fuse.py#L525) to 
```
((1 << 21) if kwargs.pop("readdir_plus", False) else 0) | \
((1 << 23) if kwargs.pop("win_file_attributes", False) else 0)
```
and adding 
`('st_flags',c_uint32)`
to the [c_stat](https://github.com/billziss-gh/fusepy/blob/master/fuse.py#L295) structure did the trick.

But for anyone reading this, it is worth to mention that using the FILE_ATTRIBUTES declared in pythons stat module and returned by `os.lstat(some_file).st_file_attributes` will not work. You have to use  

FSP_FUSE_UF_HIDDEN = 0x00008000
FSP_FUSE_UF_READONLY = 0x00001000
FSP_FUSE_UF_SYSTEM = 0x00000080
FSP_FUSE_UF_ARCHIVE = 0x00000800

as found in [inc/fuse/fuse_common.h
](https://github.com/billziss-gh/winfsp/blob/master/inc/fuse/fuse_common.h#L65)

Took some time to find this out ;)

**Comment by billziss-gh** [comment]
@robert-boulanger yes, I forgot to mention the `FSP_FUSE_UF_*` constants. They are necessary for compatibility with FUSE for macOS, which already had `chflags` and friends.

**Comment by billziss-gh** [comment]
BTW, if this works well you can also submit it as a PR.
