### ISSUE TITLE
Case sensitive filenames

### ISSUE THREAD

**Issue by frossigneux** [billziss-gh/fusepy#6]
Hello,

I would like to use Fusepy but I have a problem with filenames.
My backend is working with case sensitive filenames, but Fusepy seems to convert filenames to upper case.

Here are some extracts from my debug log:

**$ touch mountpoint/testfile**:
``
[2018-01-11 16:39:44.423462] (Dummy-1) DEBUG: Send: b'{"cmd": "file_create", "path": "/testfile"}\n'
[2018-01-11 16:39:44.437530] (Dummy-1) DEBUG: Received: b'{"status": "ok"}\n'
``

**$ ls mountpoint/testfile**:
``
python3.6m[TID=0b3c]: FFFFC384E5CA3300: >>Create [UT---C] "\TESTFILE", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=0000000000000520[PID=1b34], DesiredAccess=20080, GrantedAccess=0, ShareAccess=7
[2018-01-11 16:43:15.820282] (Dummy-1) DEBUG: Send: b'{"cmd": "stat", "path": "/TESTFILE"}\n'
[2018-01-11 16:43:15.827030] (Dummy-1) DEBUG: Received: b'{"label": "Folder or file not found.", "status": "error"}\n'
python3.6m[TID=0b3c]: FFFFC384E5CA3300: <<Create IoStatus=c0000034[0]
``

Fusepy doesn't try to use /testfile and try only with /TESTFILE (+EXE and LNK extensions).
Is it possible to use case sensitive filenames?

I have found this related issue: https://github.com/billziss-gh/winfsp/issues/26

**Comment by billziss-gh** [comment]
Windows and FUSEPY support case-sensitive file systems. These file systems work properly when mounted as a drive. Unfortunately when a file system is mounted as a directory over NTFS, Windows expects it to be case-insensitive and will UPPERCASE many of the file names sent to the file system.

This is an unfortunate but well understood Windows limitation. I recommend mounting your file system only as a drive, or making it case-insensitive if you need to mount it as a directory.

**Comment by frossigneux** [comment]
I used the _net_ command in order to mount the mountpoint as a drive and it worked!
Let me know if it is possible to create the drive directly by passing a drive letter as a mountpoint. I tried and it failed. The current solution with _net_ is satisfying so I close the issue.
Thanks!

**Comment by billziss-gh** [comment]
Since you are using FUSEPY, you should be able to pass the mount point when you construct the `FUSE` object. For example to mount on drive X pass `X:`.
