### ISSUE TITLE
Issue setting VolumePrefix 

### ISSUE THREAD

**Issue by earonesty** [billziss-gh/fusepy#9]
When I set the VolumePrefix=/my/share option via a drive-letter fuse mount, the drive mounts correctly, but it shows up as a "Disconnected Network Drive".   All of the operations (read/write/stat) seem to work OK.   

I also looked through the WinFSP code ... in an attempt to understand if there are other settings needed... but the only one I see is that a non-null VolumePrefix will cause FILE_DEVICE_NETWORK_FILE_SYSTEM to be used and to register with the Mup.

Not sure how Windows gets the status as "disconnected" on these drives... if anyone has any insight, let me know.

EDIT: I think the issue is that when you start a pyfuse mount with a volume prefix, WinFSP doesn't know it's mounted... because it wasn't started using the launcher interface.   I'm pretty sure I'd need make a new fuse option to convey this to WinFSP at start.   

The primary reason we want it to show up as a "network drive" is that some or all of the the exposed files can be located remotely  and we want windows to be nice about not generating thumbs, etc.

**Comment by billziss-gh** [comment]
There are a few pieces in the puzzle here:

- The WinFsp core, which will create a "network" drive and register it with the MUP. This means that the OS and all its processes will be able to open files using paths like `\\my\share\...` (or any associated network drive). This does not need the launcher functionality.

- The WinFsp network provider, which provides the integration with Explorer and the `net use` command. I believe that the network provider does not need any launcher functionality in order to get drive information, it only needs it when mapping or disconnecting the network drive.

What is the exact command line that you use to start the file system? Which account do you start it from? Is it elevated (run as admin)?

**Comment by earonesty** [comment]
1. I'm starting the filesystem using the FUSE(myobj, mount, options) call in python from the command line (python myfs.py).   WinFSP version is 1.2.17346.   Windows 10.0.17134 O/S.  

Here's the options used:  Starting FUSE with mount point `V:`.  Options are: `{'nothreads': False, 'foreground': True, 'raw_fi': True, 'uid': -1, 'gid': -1, 'stat_ex': True, 'case_insensitive': True, 'volname': 'Vida', 'VolumePrefix':'/cvfs/share'}`.   

2. The program is started by the user, not elevated. 

3. After tinkering a bit, I've observed these things:
   a. if I run the program without the `VolumePrefix` option, it mounts as a "drive" normally.   
   b. If I run it once with the `VolumePrefix`, explorer will always show "Disconnected Network Drive" even  if I stop and/or restart my python program *without* the prefix  - but still all file operations work fine. 
   c. When running with or without the volume prefix:`./fsptool-x64.exe lsvol` results in `V:  \Device\Volume{5345199d-75c6-11e8-b582-001a7dda7111}\cvfs\erik`

**Comment by billziss-gh** [comment]
I modified the `memory.py` example to include the `VolumePrefix` option:

```python
    fuse = FUSE(Memory(), args.mount, foreground=True, allow_other=True, VolumePrefix="/my/share")
```

Sure enough this worked:

![capture1](https://user-images.githubusercontent.com/15330948/41806130-97fdd982-766c-11e8-80d3-9c4b2f52858d.PNG)

So I am not sure why it is not working for you. Are you sure that the WinFsp Network Provider is correctly registered? What does the registry key in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order` contain?

Also if you have recently upgraded Windows 10, it annoyingly tends to "fix" some system settings. You may need to "repair" WinFsp using its installer or even uninstall and reinstall.

**Comment by earonesty** [comment]
Currently set to : RDPNP,LanmanWorkstation,webclient ... also there's no WinFsp.Np key in Services.   Repairing the installation seems to fix it.   I'm thinking of writing a repair script and firing it off ... if needed.   

Maybe something that automatically detects the problem and asks for the escalated permissions to fix it.... that the user can run any time there's an issue... or even auto-run on boot or something like that.

Thanks!

**Comment by billziss-gh** [comment]
It sounds like a Windows 10 upgrade "fixed" your system recently.

I agree that perhaps one way around this is to repair WinFsp registration keys on boot and perhaps the WinFsp Launcher service can be used for that...
